Add Merge Sort
ruddelbenito/sortysort pull request #2
Opened 2024-05-21 14:58 UTC by ruddelbenito

2024-05-27 19:17 UTC, TresTres commented on main.js
>  function combine(arrays) {
can rename this to merge

2024-05-27 23:21 UTC, TresTres requested changes

2024-05-27 23:21 UTC, TresTres commented on main.js
> +    if (arrays[0].length === 0) {
If you're going to use something multiple times, it's better to assign it to a variable.  
`arrays[0]` is accurate but it means remembering that `arrays` contains multiple arrays, and it only contains 2 arrays.  Using `let leftArr = arrays[0]` will make your code easier to follow

2024-05-27 23:21 UTC, TresTres commented on main.js
> +        if (arrays[0][leftPointer] < arrays[1][rightPointer]) {
Take a look at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/shift and see if this changes anything

2024-05-27 23:21 UTC, TresTres commented on main.js
> +        result = result.concat(arrays[0].slice(leftPointer, arrays[0].length));
I think you could use `...` spread operator here too.

2024-05-27 23:21 UTC, TresTres commented on main.js
>  function combine(arrays) {
and rename the sort function from `merge` to `mergeSort`

2024-06-01 17:36 UTC, ruddelbenito commented on main.js
>  function combine(arrays) {
Addressed

2024-06-01 17:36 UTC, ruddelbenito commented on main.js
> +    if (arrays[0].length === 0) {
Addressed

2024-06-01 17:37 UTC, ruddelbenito commented on main.js
> +        if (arrays[0][leftPointer] < arrays[1][rightPointer]) {
Addressed

2024-06-01 17:37 UTC, ruddelbenito commented on main.js
> +        result = result.concat(arrays[0].slice(leftPointer, arrays[0].length));
Addressed

2024-06-11 22:47 UTC, TresTres approved these changes

2024-06-11 23:06 UTC, merged